// This file was autogenerated by sig8tk
// Please do not edit it
#pragma once
#include "sig8.h"
//!sig8 1 FILL
extern const Sprite FILL;
#ifdef SIG8_COMPILE_RESOURCES
static const uint8_t FILL_Data[];
static const SpriteDefinition FILL_Def = {
8, 8, FILL_Data
};
const Sprite FILL = &FILL_Def;
static const uint8_t FILL_Data[] = {
0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 15, 0, 0, 0, 
0, 0, 0, 0, 0, 15, 0, 0, 
0, 0, 0, 0, 0, 0, 15, 0, 
0, 15, 15, 15, 15, 15, 15, 15, 
15, 0, 15, 15, 15, 15, 15, 0, 
15, 0, 0, 15, 15, 15, 0, 0, 
15, 0, 0, 0, 15, 0, 0, 0, 
};
#endif
//!sig8 1 LIST
extern const Sprite LIST;
#ifdef SIG8_COMPILE_RESOURCES
static const uint8_t LIST_Data[];
static const SpriteDefinition LIST_Def = {
7, 7, LIST_Data
};
const Sprite LIST = &LIST_Def;
static const uint8_t LIST_Data[] = {
0, 0, 0, 0, 0, 0, 0, 
0, 15, 0, 15, 15, 15, 0, 
0, 0, 0, 0, 0, 0, 0, 
0, 15, 0, 15, 15, 15, 0, 
0, 0, 0, 0, 0, 0, 0, 
0, 15, 0, 15, 15, 15, 0, 
0, 0, 0, 0, 0, 0, 0, 
};
#endif
//!sig8 1 PENCIL
extern const Sprite PENCIL;
#ifdef SIG8_COMPILE_RESOURCES
static const uint8_t PENCIL_Data[];
static const SpriteDefinition PENCIL_Def = {
8, 8, PENCIL_Data
};
const Sprite PENCIL = &PENCIL_Def;
static const uint8_t PENCIL_Data[] = {
0, 0, 0, 0, 0, 15, 0, 0, 
0, 0, 0, 0, 15, 15, 15, 0, 
0, 0, 0, 15, 15, 15, 15, 15, 
0, 0, 15, 15, 15, 15, 15, 0, 
0, 15, 15, 15, 15, 15, 0, 0, 
15, 0, 15, 15, 15, 0, 0, 0, 
15, 0, 0, 15, 0, 0, 0, 0, 
15, 15, 15, 0, 0, 0, 0, 0, 
};
#endif
//!sig8 1 SPRITE
extern const Sprite SPRITE;
#ifdef SIG8_COMPILE_RESOURCES
static const uint8_t SPRITE_Data[];
static const SpriteDefinition SPRITE_Def = {
7, 7, SPRITE_Data
};
const Sprite SPRITE = &SPRITE_Def;
static const uint8_t SPRITE_Data[] = {
0, 0, 0, 0, 0, 0, 0, 
0, 0, 15, 15, 15, 0, 0, 
0, 15, 0, 15, 0, 15, 0, 
0, 15, 15, 15, 15, 15, 0, 
0, 15, 15, 15, 15, 15, 0, 
0, 15, 0, 15, 0, 15, 0, 
0, 0, 0, 0, 0, 0, 0, 
};
#endif
